# Species Profile {#speciesprofile}

```{r spcoindf}

coin <- coins[["w1"]]

## df for Lv3 bar ----

df <- COINr::get_results(coin, dset = "Aggregated", tab_type = "Aggs") %>% 
  left_join(coin_11$Meta$Unit, by = "uCode")

## dfs for Lv2 decomposition

lv2list <- setNames(cols, cols) %>% 
  purrr::map(function(si) { 
    meta <- coin$Meta$Lineage %>% 
      dplyr::filter(`Sub-index` == si)
    
    data <- coin$Data$Aggregated %>% 
      dplyr::select(uCode, all_of(meta$Variable))
    list(meta = meta, data = data) 
  })

### Sensitivity
tar_load(sensitivity_imputed, 
         store = tars$envBird$sensitivity$store)

### Exposure
tar_load(exposure_indicator, 
         store = tars$envBird$exposure$store)

### Pressure
tar_load(iucn_threat, 
         store = tars$envBird$threat$store)
iucn_threat$code[is.na(iucn_threat$code)] <- "Not Assessed"
iucncode <- readxl::read_excel(
  fs::path("/mnt/envshare/data/traits/meta", "IUCN_threats.xlsx"), 
  sheet = "Threat-IUCN")
trend <- coin$Data$Raw %>% 
  dplyr::select(uCode, t_trend_score) %>% 
  dplyr::mutate(t_trend_score = case_when(
    t_trend_score == 3 ~ "Decreasing",
    t_trend_score == 2 ~ "Stable",
    t_trend_score == 1 ~ "Increasing"
  ))

## tif stack for SDM map USG ----

usg_birdstack <- terra::rast(fs::path(here::here(), usg_bird$use_tif))

## tif stack for SDM map BP ----

bp_birdstack <- terra::rast(fs::path(here::here(), bp_bird$use_tif))

```

```{r rendersp, results='asis'}

for (nm in df$uCode[order(df$uName)]) {

  cat(knitr::knit_child(
    "child/52_SpeciesProfile.Rmd",
    envir = list2env(list(
      species = nm,
      sp = gsub("_", " ", nm),
      uName = df$uName[df$uCode == nm],
      coin_name = "w1"
    )),
    quiet = TRUE
  ))
}

```
