# The cleaning process

This chapter outline the steps taken to clean the imported `bio_all` dataset. Table \@ref(tab:cleantable) then summarises how each step changed the number of taxa, records, visits, and sites.

## Cleaning steps

```{r knitenvClean, results='asis', quiet=FALSE}

rmds <- clean_summary |> 
  dplyr::filter(file.exists(rmd)) |> 
  dplyr::pull(rmd)

# Knit clean description files 
for(file in rmds){

  child <- knitr::knit_child(file)
  cat(child, sep = "\n")
  
}

```

## Summary

```{r summarytext}

cols <- c("taxa", "sites", "visits", "records")

text_init <- purrr::map_chr(cols,
                            \(x)
                            paste(head(clean_summary, 1) |> 
                                    dplyr::pull(x) |> 
                                    format(big.mark=","), x)
                            ) |> 
  envFunc::vec_to_sentence()

text_end <- purrr::map_chr(cols,
                            \(x)
                            paste(tail(clean_summary, 1) |> 
                                    dplyr::pull(x) |> 
                                    format(big.mark=","), x)
                            ) |> 
  envFunc::vec_to_sentence()


```

The initial dataset (`bio_all`) contained `r text_init`. At the end of the cleaning process, the dataset (`bio_clean`) contained `r text_end`.

```{r cleantable}

knitr::kable(clean_summary |> 
               dplyr::select(name, taxa, sites, visits, records),
             caption = "Summary of cleaning steps",
             format.args = list(big.mark = ",")) 

```


