# Taxonomy

## Overview

Taxa names were queried against the taxonomic backbone used by the Atlas of Living Australia (ALA; https://support.ala.org.au/support/solutions/articles/6000261677-taxonomy-in-the-ala). This taxonomic backbone is built from a number of taxonomy authorities such as the National Species List, Australian Plant Census, and Australian Faunal Directory. 

Taxonomy alignment is conducted by the `make_taxonomy` function in the `envClean` package `r cite_package("envClean")`, which primarily uses the ALA's `galah` package `r cite_package("galah")`. This produces a list object (named `taxonomy`) which includes a lookup table that is joined to the occurrence data to provide aligned taxonomic names used throughout the cleaning process.

Taxa names were returned at `r settings$context$grain$taxonomic` level, as specified in the envCleaned settings. Lower taxonomic ranks are ignored (e.g. for species level, *Acanthiza iredalei rosinae* and *Acanthiza iredalei hedleyi* are both binned to *Acanthiza iredalei*). Higher ranks are kept in the taxonomy data, but any record that could not be matched to a name at the specified level are removed in the [region taxa](#region-taxa) filtering step. 


### Searched names

Prior to querying against ALA, `make_taxonomy` makes changes to the data to assist galah's `search_taxa` function and to only return relevant taxa. These changes include (but see help for `envClean::make_taxonomy` for full details):

-   any record that contains any of the following text in its name (ignoring case) is removed (i.e. rows are removed):
    -   `r paste0(formals(envClean::make_taxonomy)$remove_taxa, collapse = "\n    + ")`
-   any of the following text in a taxon name is removed using regular expressions (via `gsub`; i.e. text is removed):
    -   quotation marks
    -   question marks
    -   double hyphens '--'
    -   trailing 'species', 'spec.', 'subspecies', 'spp.', 'sp.', 'form', 'race' (and other variations)
    -   leading or trailing spaces
    -   'unknown', 'dead', 'cultivar', 'complex', '(nc)', 'aff.'
-   any text including and after ' x ' or ' X ' is removed (thus any hybrids are most likely assigned to the first taxon recorded within the hybrid)


## Taxonomy cleaning process {#taxonomy-cleaning}

Taxonomy search and alignment is conducted early in the cleaning process, with `make_taxonomy` taking `clean_start` as its data input. The `taxonomy` object is created using the following steps, then used to provide a consistent, aligned `taxa` column for the rest of the cleaning process.

### External overrides

The ALA taxonomy and galah's `search_taxa` function may return a name that is wrong or not able to be matched. In addition, some names returned need to be manually reassigned to reflect how they appear in threatened species legislation. These cases are handled by taxonomy 'overrides' that are created outside of the `envCleaned` project, imported, and included as an argument to `make_taxonomy`.

See Appendix [Taxonomy overrides] for the full list of external overrides.

#### Manual overrides

Occasionally, duplicate accepted taxon names exist within the ALA taxonomy for the same entity due to taxonomic updates that are in progress, unresolved taxonomies, or recording errors (e.g. recording an international related species instead of the Australian species). Where duplicate accepted taxon names were identified, these were manually combined to the most recently accepted binomial.

For example, the Brolga is accepted in ALA as both *Grus rubicunda* and *Antigone rubicunda*. Both genera have been used in the past, and the original but then superseded *Antigone* has recently been revived following DNA analysis. To avoid Brolga records being separated and treated as two separate species, when in reality all records come from only one species, a manual fix was added to assign both binomials to the more recently-accepted *Antigone rubicunda*. Similarly, the ALA taxonomic backbone would rarely return an incorrect taxon name. When identified, manual fixes were also applied to these taxa.

Manual fixes are stored as the `taxonomy_overrides` data frame in the `envClean` package.

#### Act overrides

State and national threatened species legislation (NPW Act and EPBC Act, respectively) list species using names that may not appear in taxonomic backbones, or are matched to different name. Many listed names include strings such as 'sp.' or 'var.' that are usually removed (see [Searched names] above), but need to be kept to correctly match the legislation. Other listed names are outdated (e.g. brolga as above), or refer to a population or subspecies by geographic location (e.g. the EPBC listing for mala/rufous hare-wallaby as "*Lagorchestes hirsutus Central Australian subspecies*").

Taxonomy overrides to align taxa to their listed name are generated by the `envStatus` project [@RN4604] and imported as an rds file. 

### First pass taxonomy

A 'first pass' taxonomy matching is conducted using `make_taxonomy`, taking `clean_start` as its data input and the external overrides. 


### Unmatched names

Some taxa names are not found by `search_taxa` in the first pass of taxonomy matching. These names are collected and checked by a similar function in the `rgbif` package, `name_backbone` (`r cite_package("rgbif")`), via the `envClean` function `make_unmatched_overrides`. GBIF can have better handling of 'fuzzy matching' such as spelling errors and case sensitivity. This returns a new original name - its 'override name' - to search in ALA. If still no match is found, the override name 'name' is applied so that the record remains available for interrogation, but it will not be used in any further processes in `envCleaned` or downstream projects. 

```{r unmatched-tbl}

arrow::open_dataset(fs::path("..", "..", "..", "..", "data", "taxonomy", "galah.parquet")) |>
 dplyr::filter(override) |>
 dplyr::anti_join(overrides_external) |> 
 dplyr::select(original_name
               , taxa_to_search = scientific_name
               , use_species = scientific_name
               ) |>
  dplyr::collect() |>
  knitr::kable(caption = "Taxa names (original_name) that were not originally found by `galah::search_taxa()`, but were returned by the GBIF Backbone Taxonomy. The name returned by GBIF was used then used in `galah::search_taxa()` to return the `use_species` name."
               , format = "html"
               ) |>
  kableExtra::kable_styling("striped")

```


### Final taxonomy

A final call to `make_taxonomy` is made using the `clean_start` data, along with names from distribution data collected by the `envDistribution` package `r cite_package("envDistribution")` (to be used in [filter by distribution](#fbd)). This step uses both external overrides and unmatched overrides.

The returned `taxonomy` is a list object with

-   the table similar to that returned by `search_taxa` (plus some internal processing columns such as override information)
-   a lookup table, with an entry for every original name, searched name, and returned names (i.e. `taxa`)
-   full taxonomy information (i.e. kingdom, class, family, etc) for each returned taxa




